# config.toml

[default]
app_name = "FastAPI Application"
api_version = "v1"
enable_logging = true

[development]
database_url = "mongodb://root:example@mongo-db:27017"
jwt_secret_key = "Test"
debug = true

[production]
debug = false
optimize = true
