FROM redis:latest

# Set any additional configuration options here
# For example, you can specify a custom Redis configuration file
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Expose the Redis port
EXPOSE 6379

# Run Redis when the container starts
CMD ["redis-server"]